version: "3"
services:
      app:
            build:
                  context: .
                  dockerfile: Dockerfile
            volumes:
                  - ./source:/var/www/html
            depends_on:
                  - mysql
            networks:
                  - laravel

      web:
            image: nginx:stable-alpine
            ports:
                  - "8000:80"
            volumes:
                  - ./source:/var/www/html
                  - ./nginx.conf:/etc/nginx/conf.d/default.conf
            depends_on:
                  - app
            networks:
                  - laravel

      mysql:
            image: mysql:8
            restart: unless-stopped
            environment:
                  MYSQL_DATABASE: laravel
                  MYSQL_ROOT_PASSWORD: root
                  MYSQL_PASSWORD: secret
                  MYSQL_USER: laravel
            ports:
                  - "3307:3306"
            volumes:
                  - dbdata:/var/lib/mysql
            networks:
                  - laravel

networks:
      laravel:

volumes:
      dbdata:
